const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let expr='',memory=Number(localStorage.getItem('calcMemory')||0),angle=localStorage.getItem('calcAngle')||'DEG',mode='basic';
const history=JSON.parse(localStorage.getItem('calcHistory')||'[]');
const settings={theme:localStorage.getItem('calcTheme')||'system',haptic:localStorage.getItem('calcHaptic')!=='false'};
function vibrate(){if(settings.haptic&&navigator.vibrate)navigator.vibrate(8)}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),1800)}
function display(){
 $('#expression').textContent=expr||'0';let r='0';try{if(expr)r=fmt(evaluate(expr))}catch{}$('#result').textContent=r;
 $('#memoryLabel').classList.toggle('hidden',Math.abs(memory)<1e-12);$('#angleLabel').textContent=angle;
}
function fmt(n){if(!Number.isFinite(n))throw Error('Math error');if(Math.abs(n)<1e-12)n=0;return Number(n.toPrecision(12)).toString()}
function tokenize(s){const t=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}if(/[0-9.]/.test(s[i])){let j=i;while(j<s.length&&/[0-9.]/.test(s[j]))j++;const n=Number(s.slice(i,j));if(Number.isNaN(n))throw Error();t.push({t:'n',v:n});i=j;continue}if(s.startsWith('sin(',i)||s.startsWith('cos(',i)||s.startsWith('tan(',i)||s.startsWith('log(',i)||s.startsWith('ln(',i)){let f=s.slice(i,i+3);if(s.startsWith('log(',i))f='log';if(s.startsWith('sin(',i)||s.startsWith('cos(',i)||s.startsWith('tan(',i)){}t.push({t:'f',v:f});t.push({t:'op',v:'('});i+=f.length+1;continue}if(s[i]==='√'){t.push({t:'f',v:'sqrt'});i++;continue}if(s[i]==='π'){t.push({t:'n',v:Math.PI});i++;continue}if(s[i]==='×'||s[i]==='÷'||s[i]==='−'||s[i]==='+'||s[i]==='^'||s[i]==='('||s[i]===')'){t.push({t:'op',v:s[i]});i++;continue}throw Error('Invalid');}return t}
function evaluate(s){let t=tokenize(s),p=0;function primary(){let x=t[p++];if(!x)throw Error();if(x.t==='n')return x.v;if(x.v==='('){let v=add();if(!t[p]||t[p].v!==')')throw Error();p++;return v}if(x.t==='f'){let v=primary();if(x.v==='sin')return Math.sin(angle==='DEG'?v*Math.PI/180:v);if(x.v==='cos')return Math.cos(angle==='DEG'?v*Math.PI/180:v);if(x.v==='tan')return Math.tan(angle==='DEG'?v*Math.PI/180:v);if(x.v==='log')return Math.log10(v);if(x.v==='ln')return Math.log(v);return Math.sqrt(v)}throw Error()}function power(){let v=primary();while(t[p]?.v==='^'){p++;v=Math.pow(v,power())}return v}function mul(){let v=power();while(t[p]&&['×','÷'].includes(t[p].v)){let o=t[p++].v,a=power();if(o==='÷'&&a===0)throw Error();v=o==='×'?v*a:v/a}return v}function add(){let v=mul();while(t[p]&&['+','−'].includes(t[p].v)){let o=t[p++].v,a=mul();v=o==='+'?v+a:v-a}return v}let v=add();if(p!==t.length)throw Error();return v}
function append(v){if(v==='('&&expr&&/[0-9π)]$/.test(expr))expr+='×';if(v==='π'&&expr&&/[0-9π)]$/.test(expr))expr+='×';expr+=v;display();vibrate()}
function clear(){expr='';display();vibrate()}
function back(){expr=expr.slice(0,-1);display();vibrate()}
function percent(){try{expr=fmt(evaluate(expr)/100);display();vibrate()}catch{toast('Enter a valid number first')}}
function sign(){try{const v=fmt(-evaluate(expr));expr=v;display();vibrate()}catch{toast('Enter a valid number first')}}
function equals(){try{const e=expr||'0',v=fmt(evaluate(e));history.unshift({e,v});history.splice(30);localStorage.setItem('calcHistory',JSON.stringify(history));expr=v;renderHistory();display();vibrate()}catch{toast('Invalid expression')}}
function renderHistory(){const box=$('#historyList');if(!history.length){box.innerHTML='<div class="empty">Your calculations will appear here.</div>';return}box.innerHTML=history.map((h,i)=>`<div class="history-item"><small>${escapeHtml(h.e)}</small><button data-history="${i}">${escapeHtml(h.v)}</button></div>`).join('');$('[data-history]')?.parentElement;$$('[data-history]').forEach(b=>b.onclick=()=>{expr=history[+b.dataset.history].v;display()})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$$('[data-value]').forEach(b=>b.onclick=()=>append(b.dataset.value));$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='clear')clear();if(a==='backspace')back();if(a==='percent')percent();if(a==='sign')sign();if(a==='decimal'){if(!/\d$/.test(expr))append('0.');else append('.')}if(a==='equals')equals();if(a==='angle'){angle=angle==='DEG'?'RAD':'DEG';save();display()}if(['mc','mr','mplus','mminus'].includes(a))memoryAction(a)});
function memoryAction(a){try{if(a==='mc')memory=0;if(a==='mr')expr+=fmt(memory);if(a==='mplus')memory+=evaluate(expr||'0');if(a==='mminus')memory-=evaluate(expr||'0');localStorage.setItem('calcMemory',memory);display();vibrate()}catch{toast('Memory action needs a valid value')}}
$$('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('.mode').forEach(x=>x.classList.toggle('active',x===b));$('#basicPanel').classList.toggle('hidden',mode!=='basic');$('#scientificPanel').classList.toggle('hidden',mode!=='scientific');$('#toolsPanel').classList.toggle('hidden',mode!=='tools')});
function save(){localStorage.setItem('calcAngle',angle);localStorage.setItem('calcTheme',settings.theme);localStorage.setItem('calcHaptic',settings.haptic)}
function applyTheme(){let t=settings.theme;if(t==='system')t=matchMedia('(prefers-color-scheme:light)').matches?'light':'dark';document.body.classList.toggle('light',t==='light');$('#themeSelect').value=settings.theme}
$('#themeBtn').onclick=()=>{settings.theme=settings.theme==='dark'?'light':settings.theme==='light'?'system':'dark';save();applyTheme()};
$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#closeSettings').onclick=()=>$('#settingsDialog').close();$('#themeSelect').onchange=e=>{settings.theme=e.target.value;save();applyTheme()};$('#angleSelect').onchange=e=>{angle=e.target.value;save();display()};$('#hapticToggle').onchange=e=>{settings.haptic=e.target.checked;save()};
$('#clearHistory').onclick=()=>{history.length=0;localStorage.removeItem('calcHistory');renderHistory()};$('#shareResult').onclick=async()=>{const text=$('#result').textContent;if(navigator.share){await navigator.share({title:'Calculator result',text}).catch(()=>{})}else{await navigator.clipboard?.writeText(text);toast('Result copied')}};
const units={length:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,in:.0254},weight:{kg:1,g:.001,lb:.45359237,oz:.0283495231},temperature:{C:'C',F:'F',K:'K'}};
function fillUnits(){const type=$('#unitType').value,opts=Object.keys(units[type]);['#unitFrom','#unitTo'].forEach((id,k)=>{$(id).innerHTML=opts.map(x=>`<option>${x}</option>`).join('');$(id).value=opts[k]||opts[0]});convertUnit()}
function convertUnit(){const type=$('#unitType').value,n=Number($('#unitInput').value),a=$('#unitFrom').value,b=$('#unitTo').value;if(!Number.isFinite(n)){$('#unitResult').textContent='—';return}let r;if(type==='temperature'){let c=a==='C'?n:a==='F'?(n-32)*5/9:n-273.15;r=b==='C'?c:b==='F'?c*9/5+32:c+273.15}else r=n*units[type][a]/units[type][b];$('#unitResult').textContent=fmt(r)+' '+b}
$('#unitType').onchange=fillUnits;$('#unitInput').oninput=convertUnit;$('#unitFrom').onchange=convertUnit;$('#unitTo').onchange=convertUnit;
$('#currencyBtn').onclick=async()=>{const a=Number($('#currencyAmount').value),from=$('#currencyFrom').value,to=$('#currencyTo').value,out=$('#currencyResult');if(!Number.isFinite(a)){out.textContent='Enter an amount.';return}out.textContent='Loading live rate…';try{const res=await fetch(`https://open.er-api.com/v6/latest/${from}`);if(!res.ok)throw Error();const data=await res.json();const rate=data.rates?.[to];if(!rate)throw Error();out.textContent=`${fmt(a*rate)} ${to}  •  1 ${from} = ${fmt(rate)} ${to}`;const d=data.time_last_update_utc||'Updated recently';out.title=d}catch{out.textContent='Live rate unavailable. Check internet and try again.'}};
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key;if(/[0-9]/.test(k))append(k);else if(k==='+')append('+');else if(k==='-')append('−');else if(k==='*')append('×');else if(k==='/'){e.preventDefault();append('÷')}else if(k==='.')append('.');else if(k==='Enter'||k==='=')equals();else if(k==='Backspace')back();else if(k==='Escape')clear();else if(k==='%')percent()});
renderHistory();$('#angleSelect').value=angle;$('#hapticToggle').checked=settings.haptic;fillUnits();applyTheme();display();